TARGET_HEADLESS = neucoind
TARGET_QT = neucoin-qt

MAKEFILE = Makefile.unix

include Makefile.default

CXXFLAGS += $(shell pkg-config Qt5Core Qt5Gui Qt5Widgets --cflags)
CXXFLAGS += -fPIE

LIBRARIES_HEADLESS := rt pthread $(LIBRARIES_HEADLESS)
LIBRARIES_QT := rt pthread $(LIBRARIES_QT)

include Makefile.common
