TARGET_HEADLESS = neucoind
TARGET_QT = neucoin-qt

MAKEFILE = Makefile.unix

QT_MID_SUFFIX = 5

include Makefile.default

CXXFLAGS += -fPIE

ifneq ($(NO_QT),1)
  CXXFLAGS += $(shell pkg-config Qt5Core Qt5Gui Qt5Widgets --cflags)
endif

LIBRARIES_HEADLESS := rt pthread $(LIBRARIES_HEADLESS)
LIBRARIES_QT := rt pthread $(LIBRARIES_QT)

include Makefile.common
